# Generated by Django 3.2.5 on 2022-05-19 03:16

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('isbn', models.CharField(max_length=10, primary_key=sqlalchemy.sql.expression.true, serialize=False, unique=sqlalchemy.sql.expression.true)),
                ('bookname', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=sqlalchemy.sql.expression.true, serialize=False, unique=sqlalchemy.sql.expression.true)),
                ('username', models.CharField(max_length=20, null=sqlalchemy.sql.expression.false, unique=True)),
                ('email', models.EmailField(max_length=254, null=sqlalchemy.sql.expression.false, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('interests', models.CharField(max_length=150)),
            ],
        ),
    ]
