# Generated by Django 3.2.5 on 2022-05-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
