# Generated by Django 3.2.5 on 2022-05-26 22:49

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.AutoField(primary_key=True, serialize=False, unique=sqlalchemy.sql.expression.true),
        ),
    ]
