# Generated by Django 3.2.5 on 2022-05-27 00:52

from django.db import migrations, models
import home.models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(null=sqlalchemy.sql.expression.true, upload_to='', verbose_name=home.models.upload_to),
        ),
    ]
