# Generated by Django 3.2.5 on 2022-05-27 00:56

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(default='Unknown', max_length=50, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(max_length=50, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=30, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='books',
            name='cost',
            field=models.IntegerField(default=0, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=150, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=30, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='books',
            name='sellerid',
            field=models.CharField(default='0000000001', max_length=10, null=sqlalchemy.sql.expression.true),
        ),
    ]
