# Generated by Django 3.2.5 on 2022-05-27 01:02

from django.db import migrations, models
import home.models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220527_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(default='My book', max_length=50, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='', verbose_name=home.models.upload_to),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='sellerid',
            field=models.CharField(default='0000000001', max_length=10),
        ),
    ]
