# Generated by Django 3.2.5 on 2022-06-06 16:45

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_books_sellerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatHistory',
            fields=[
                ('chatid', models.AutoField(primary_key=True, serialize=False, unique=sqlalchemy.sql.expression.true)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100000)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatReceiver', to='home.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatSender', to='home.users')),
            ],
        ),
    ]
