# Generated by Django 3.2.5 on 2022-06-14 18:33

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=sqlalchemy.sql.expression.true, serialize=False, unique=sqlalchemy.sql.expression.true),
        ),
    ]
