# Generated by Django 3.2.5 on 2022-06-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_books_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
