# Generated by Django 3.2.5 on 2022-07-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_users_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='wishlist',
            field=models.CharField(default='', max_length=100000000),
        ),
    ]
