# Generated by Django 3.2.5 on 2022-07-10 16:09

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_users_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='wishlist',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(default='My book', max_length=500, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(default='Unknown', max_length=1550),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
