# Generated by Django 3.2.5 on 2022-07-13 14:25

from django.db import migrations, models
import django.db.models.deletion
import home.models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220710_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=sqlalchemy.sql.expression.true, related_name='keysid', serialize=False, to='home.users')),
                ('publicKey', models.FileField(upload_to='', verbose_name=home.models.publicKeyFile)),
                ('privateKey', models.FileField(upload_to='', verbose_name=home.models.privateKeyFile)),
            ],
        ),
    ]
