# Generated by Django 3.2.5 on 2022-07-13 14:57

from django.db import migrations, models
import django.db.models.deletion
import home.models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keysid', to='home.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keys',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='keys',
            name='privateKey',
            field=models.FileField(null=sqlalchemy.sql.expression.true, upload_to='', verbose_name=home.models.privateKeyFile),
        ),
        migrations.AlterField(
            model_name='keys',
            name='publicKey',
            field=models.FileField(null=sqlalchemy.sql.expression.true, upload_to='', verbose_name=home.models.publicKeyFile),
        ),
    ]
