# Generated by Django 3.2.5 on 2022-07-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20220714_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='message',
            field=models.BinaryField(max_length=100000000),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='messageReceiver',
            field=models.BinaryField(max_length=100000000),
        ),
    ]
