# Generated by Django 3.2.5 on 2022-07-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220714_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='message',
            field=models.CharField(max_length=100000000),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='messageReceiver',
            field=models.CharField(max_length=100000000),
        ),
    ]
