# Generated by Django 3.2.5 on 2022-07-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220714_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='message',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='messageReceiver',
            field=models.BinaryField(),
        ),
    ]
