# Generated by Django 3.2.5 on 2022-07-15 00:42

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220715_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='message',
            field=models.BinaryField(null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='messageReceiver',
            field=models.BinaryField(null=sqlalchemy.sql.expression.false),
        ),
    ]
