# Generated by Django 3.2.5 on 2022-07-15 15:47

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220715_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='message',
            field=models.CharField(max_length=10000000, null=sqlalchemy.sql.expression.false),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='messageReceiver',
            field=models.CharField(max_length=10000000, null=sqlalchemy.sql.expression.false),
        ),
    ]
