# Generated by Django 3.2.5 on 2022-07-16 02:37

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220715_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='chatid',
            field=models.AutoField(default='1', primary_key=True, serialize=False, unique=sqlalchemy.sql.expression.true),
        ),
    ]
