# Generated by Django 3.2.5 on 2022-07-16 02:42

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220716_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
    ]
