# Generated by Django 3.2.5 on 2022-07-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220716_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='messageReceiver',
        ),
    ]
